### ISSUE TITLE
Unable to use react-scripts 3.4.0 with Linc

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#27]
**Describe the bug**
Upgrading to `react-scripts` 3.4.0 fails on build. I suspect this is due to the `rewired` configuration added by @geelen but as I'm not 100% sure what the configuration does, I'm looking for a little help to resolve!

The original change is in https://github.com/digivizer/frontend/commit/556d495740c0888da7ddd23298a834d7e852c63c

```
/tmp/src/config-overrides.js:3
const isStaticPath = str => str && str.startsWith("static/");
^
TypeError: str.startsWith is not a function
at isStaticPath (/tmp/src/config-overrides.js:3:40)
at Object.keys.forEach.key (/tmp/src/config-overrides.js:34:13)
at Array.forEach (<anonymous>)
at config.plugins.forEach.plugin (/tmp/src/config-overrides.js:33:35)
at Array.forEach (<anonymous>)
at Object.override [as webpack] (/tmp/src/config-overrides.js:31:18)
at require.cache.(anonymous function).exports.isWebpackFactory (/tmp/src/node_modules/react-app-rewired/scripts/build.js:19:24)
at Object.<anonymous> (/tmp/src/node_modules/react-scripts/scripts/build.js:63:16)
at Module._compile (internal/modules/cjs/loader.js:701:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
```

**To Reproduce**
1. Upgrade to `react-scripts` 3.4.0
2. Build in Linc

**Expected behavior**
I should be able to upgrade without error.

**Comment by evanderkoogh** [comment]
@geelen will have a look at this our tonight/his morning. Hopefully should be solved by the time you wake up tomorrow ;)

**Comment by geelen** [comment]
This should be fixed by upgrading to FAB v1 alpha. Instructions left in https://github.com/bitgenics/linc/issues/26#issuecomment-600875263 but I'll leave this issue open as well in case there's any hiccups.

**Comment by evanderkoogh** [comment]
Hey @qnm, did you get around to upgrading to the new FAB tooling? @geelen rewrote it from scratch to be more modular, reuseable and fixes a lot of issues with the older tooling.

We are currently gearing up for a public release, so we are working on the docs a lot. So if you need any help, please give a shout: https://fab.dev/

**Comment by qnm** [comment]
Hey @evanderkoogh 

I never got around to merging it and now I’ve upgraded to the latest version, hit a wee snag and dropped an update in the other issue referenced above.

**Comment by qnm** [comment]
This is confirmed working with FABv1. Thanks!
